my_second_pjt/accounts/urls.py
from django.urls import path
from accounts import views

app_name = "accounts"
urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('delete/', views.delete, name="delete"),
    path('update/', views.update, name="update"),
    path('password/', views.change_password, name="change_password"),
]

my_second_pjt/articles/urls.py
from django.urls import path
from articles import views

app_name = "articles"
urlpatterns = [
    path('', views.articles, name="articles"),
    path('<int:pk>/', views.detail, name="detail"),
    path('create/', views.create, name="create"),
    path('<int:pk>/update/', views.update, name="update"),
	path('<int:pk>/delete/', views.delete, name="delete"),
    path('data-throw/', views.data_throw, name="data-throw"),
    path('data-catch/', views.data_catch, name="data-catch"),
]

my_second_pjt/my_second_pjt/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static
from articles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index, name='index'),
    path('hello/', views.hello, name="hello"),
    path('articles/', include('articles.urls')),
    path('users/', include('users.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

my_second_pjt/users/urls.py
from django.urls import path
from users import views

app_name = "users"
urlpatterns = [
    path("", views.users, name='users'),
    path('<str:username>/', views.profile, name='profile'),
]

my_second_pjt/accounts/models.py
from django.db import models

# Create your models here.

my_second_pjt/articles/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to="images/", blank=True)

    def __str__(self):
        return self.title

my_second_pjt/users/models.py
from django.db import models

# Create your models here.

my_second_pjt/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm
from django.contrib.auth import get_user_model
from django.urls import reverse


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = (
            "username",
            "email",
            "first_name",
            "last_name",
        )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self.fields.get("password"):
            password_help_text = (
                "You can change the password " '<a href="{}">here</a>.'
            ).format(f"{reverse('accounts:change_password')}")
            self.fields["password"].help_text = password_help_text

my_second_pjt/articles/forms.py
from django import forms
from articles.models import Article


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = "__all__"

my_second_pjt/accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods, require_POST
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import (
    AuthenticationForm,
    UserCreationForm,
    PasswordChangeForm,
)
from accounts.forms import CustomUserChangeForm


@require_http_methods(["GET", "POST"])
def login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            next_path = request.GET.get("next") or "index"
            return redirect(next_path)
    else:
        form = AuthenticationForm()
    context = {"form": form}
    return render(request, 'accounts/login.html', context)


@login_required
@require_POST
def logout(request):
    auth_logout(request)
    return redirect('index')


@require_http_methods(["GET", "POST"])
def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('index')
    else:
        form = UserCreationForm()
    context = {'form': form}
    return render(request, 'accounts/signup.html', context)


@login_required
@require_POST
def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('index')


@login_required
@require_http_methods(["GET", "POST"])
def update(request):
    if request.method == "POST":
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {"form": form}
    return render(request, 'accounts/update.html', context)


@login_required
@require_http_methods(["GET", "POST"])
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('index')
    else:
        form = PasswordChangeForm(request.user)
    context = {"form": form}
    return render(request, 'accounts/change_password.html', context)

my_second_pjt/articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods, require_POST
from articles.models import Article
from articles.forms import ArticleForm


def index(request):
    return render(request, 'articles/index.html')


def hello(request):
    name = "T문"
    tags = ["#귀여운", "#순수한"]
    conditions = {
        "today": "피곤",
        "yesterday": "왕피곤",
        "tomorrow": "???"
    }
    context = {
        "name": name,
        "tags": tags,
        "conditions": conditions
    }
    return render(request, 'articles/hello.html', context)


def articles(request):
    articles = Article.objects.all()
    context = {
        "articles": articles,
    }
    return render(request, 'articles/articles.html', context)


def detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    context = {
        "article": article
    }
    return render(request, 'articles/detail.html', context)


@login_required
@require_http_methods(["GET", "POST"])
def create(request):
    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save()
            return redirect("articles:detail", article.pk)
    else:
        form = ArticleForm()

        context = {"form": form}
    return render(request, 'articles/create.html', context)


@login_required
@require_http_methods(["GET", "POST"])
def update(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            article = form.save()
            return redirect("articles:detail", article.pk)
    else:
        form = ArticleForm(instance=article)

    context = {
        "form": form,
        "article": article,
    }
    return render(request, 'articles/update.html', context)


@login_required
@require_http_methods(["GET", "POST"])
def delete(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if request.method == "POST":
        article.delete()
        return redirect('articles:articles')


def data_throw(request):
    return render(request, 'articles/data-throw.html')


def data_catch(request):
    message = request.GET.get("message")
    context = {"message": message}
    return render(request, 'articles/data-catch.html', context)

my_second_pjt/users/views.py
from django.shortcuts import render


def users(request):
    return render(request, 'users/users.html')


def profile(request, username):
    context = {'username': username}
    return render(request, 'users/profile.html', context)

my_second_pjt/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
<h1> 비밀번호 변경 </h1>
<form action="{% url 'accounts:change_password' %}" method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">비밀번호 변경</button>
</form>
{% endblock content %}

my_second_pjt/accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<h1>로그인</h1>

<form action="" method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit"> 로그인 </button>
</form>
{% endblock content%}

my_second_pjt/accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<h1>회원 가입</h1>
<form action="{% url 'accounts:signup' %}" method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">회원가입</button>
</form>
{% endblock content %}

my_second_pjt/accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
<h1>정보 수정</h1>
<form action="{% url 'accounts:update' %}" method="POST">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit">수정</button>
</form>
{% endblock content %}

my_second_pjt/articles/templates/articles/articles.html
{% extends 'base.html' %}

{% block content %}
<h1>Articles</h1>
<a href="{% url 'articles:create' %}">글 작성</a>
{% for article in articles %}
<a href="{% url 'articles:detail' article.pk %}">
	<p>[{{ article.pk }}]{{ article.title }}</p>
</a>
{% endfor %}

{% endblock content %}

my_second_pjt/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
<h2>글 작성</h2>
<form action="{% url 'articles:create'%}" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit"> 저장 </button>
</form>
{% endblock content %}

my_second_pjt/articles/templates/articles/data-catch.html
{% extends 'base.html' %}

{% block content %}
<h2>Data Catch</h2>
<p>메세지 : {{ message }}</p>
<button type="submit"><a href="{% url 'articles:data-throw' %}"> 다시 던지러 가기</a></button>
{% endblock content %}

my_second_pjt/articles/templates/articles/data-throw.html
{% extends 'base.html' %}

{% block content %}
<h2>Data Throw</h2>
<form action="{% url 'articles:data-catch' %}" method="GET">
	<label for="message"> 메세지 </label>
	<input type="text" name="message" id="message">
	<button type="submit">전송</button>
</form>
{% endblock content %}

my_second_pjt/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
<h2>Article Detail Page</h2>
<p>제목: {{ article.title }}</p>
{% if article.image %}
<img src="{{ article.image.url }}">
{% endif %}
<p>내용: {{ article.content }}</p>
<p>생성일시: {{ article.created_at }}</p>
<p>수정일시: {{ article.updated_at }}</p>

<a href="{% url 'articles:articles' %}">목록으로</a>
<a href="{% url 'articles:update' article.pk %}"> 수정 </a>
<form action="{% url 'articles:delete' article.pk %}" method="POST">
	{% csrf_token %}
	<button type="submit">삭제</button>
</form>
{% endblock content %}

my_second_pjt/articles/templates/articles/hello.html
{% extends 'base.html' %}

{% block content %}
<h1>Hello, {{ name }}!</h1>
<li>{{ tags|join:", " }}</li>
<li>기분 : {{ conditions.today }}</li>
<ul>
	{% for condition in conditions.items %}
	<li>{{ condition.0}} - {{ condition.1 }}</li>
	{% endfor %}
</ul>

{% endblock content%}

my_second_pjt/articles/templates/articles/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1> INDEX </h1>
<img src="{% static  "articles/sunset.jpg" %}">
<ul>
	<li><a href="{% url 'users:users'%}">User</a></li>
	<li><a href="{% url 'articles:articles' %}">Articles</a></li>
</ul>
{% endblock content%}

my_second_pjt/articles/templates/articles/update.html
{% extends 'base.html' %}

{% block content %}
<h2> Update Page </h2>
<form action="{% url 'articles:update' article.pk %}" method="POST" enctype="multipart/form-data">
	{% csrf_token %}
	{{ form.as_p }}
	<button type="submit"> 수정 </button>
</form>
{% endblock content %}

my_second_pjt/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link rel="stylesheet" href="{% static "css/style.css" %}">
	<title>Document</title>
</head>

<body>
	<div class="navbar">
		{% if request.user.is_authenticated %}
		<h3>안녕하세요, {{ user }}님</h3>
		<form action="{% url 'accounts:logout' %}" method="POST">
			{% csrf_token %}
			<input type="submit" value="로그아웃">
		</form>
		<form action="{% url 'accounts:delete' %}" method="POST">
			{% csrf_token %}
			<input type="submit" value="회원탈퇴">
		</form>
		<a href="{% url 'accounts:update' %}"> 회원 정보 수정 </a>
		{% else %}
		<a href="{% url 'accounts:login' %}">로그인</a>
		<a href="{% url 'accounts:signup' %}">회원가입</a>
		{% endif %}
	</div>

	<div class="container">
		<a href="{% url 'index' %}">INDEX</a>
		{% block content %}
		{% endblock content %}
	</div>
</body>

</html>

my_second_pjt/users/templates/users/profile.html
{% extends 'base.html' %}

{% block content %}
<h2>{{ username }}의 프로필 페이지</h2>
<h3> username : {{ username }}</h3>
{% endblock content %}

my_second_pjt/users/templates/users/users.html
{% extends 'base.html' %}

{% block content %}
<h1> Users Page </h1>
{% endblock content %}